import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { Providers } from "./_providers/providers";
import { Session } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type RootLayoutProps = {
  children: React.ReactNode 
}

// NOTE: This is a hack to get around the fact that next build doesn't thing RootLayoutPropsExtended is a valid type
// session should always be there due to middleware
type RootLayoutPropsExtended = RootLayoutProps & { session: Session }

export default function RootLayout(props: RootLayoutProps | RootLayoutPropsExtended) {
  
  const { children, session } = {
    ...props,
    session: undefined
  }
  
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Providers session={session!}> 
          {children}
        </Providers>
      </body>
    </html>
  );
}
